version: 2.1

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            git fetch origin master
            git config --global user.email "hamlet.mikaelyan@codesignal.com"
            git config --global user.name "Hamlet"
            git merge origin/master
            echo 'hello'
            cd checker
            npm install
            npm run validate

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
  schedule-workflow:
    triggers:
      - schedule:
          cron: "21 * * * *"
          filters:
            branches:
              only:
                - validationBranch
    jobs:
      - build1
