version: 2

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            git config --global user.email hamlet.mikaelyan@codesignal.com
            git config --global user.name "Hamlet"
            git fetch origin
            git merge origin/master
            echo 'hello'
            cd checker
            npm install
            npm run validate

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
