version: 2.1

orbs:
  git: pagerduty/git@0.0.3

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - rebase_on_master
      - run:
          command: |
            echo 'hello'
            cd checker
            npm install
            npm run validate

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
