version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            cd checker
            npm ci
            ts-node checkAll.ts

workflows:
  version: 2
  schedule-workflow:
    triggers:
      - schedule:
          cron: "04 * * * *"
          filters:
            branches:
              only:
                - newBranch
    jobs:
      - build