version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            cd checker
            mkdir tmp
            echo "Some Line" > tmp/newfile.txt
      - persist_to_workspace:
          root: .
          paths:
            - *

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            cd checker
            cd tmp
            cat newfile.txt

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          name: b1
      - build:
          name: b2
      - test:
          requires:
            - b1
            - b2
