version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - persist_to_workspace:
          root: checker
          path:
            - tmp
      - run:
          command: |
            cd checker
            echo "Some Line" > /tmp/newfile.txt

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: /checker/tmp
      - run:
          command: |
            cd tmp
            cat newfile.txt

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
