version: 2
orbs:
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: cd checker
      - run: npm ci
      - run: ts-node checkAll.ts

workflows:
  version: 2
  schedule-workflow:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
