version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            cd checker
            mkdir tmp
            cd tmp
            echo "Some Line" > newfile.txt
      - store_artifacts:
          path: /checker/tmp/newfile.txt

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            cd checker
            cd tmp
            cat newfile.txt

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
