version: 2
orbs:
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd checker
      - run: ls -l

workflows:
  version: 2
  schedule-workflow:
    triggers:
      - schedule:
          cron: "46 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
