version: 2.1

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            git fetch origin master
            git merge origin/master
            echo 'hello'
            cd checker
            npm install
            npm run validate
  build2:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            echo 'hello'
            cd checker
            npm install
            npm run validate


workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
      - build2
  schedule-workflow:
    triggers:
      - schedule:
          cron: "4,6,8,10,12 * * * *"
          filters:
            branches:
              only:
                - validationBranch
    jobs:
      - build1:
          filters:
            branches:
              only:
                - validationBranch
