version: 2

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            echo 'aaaa'
            git pull origin newBranch

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
