version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  schedule-workflow:
    triggers:
      - schedule:
          cron: "23 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
