version: 2
orbs:
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            cd checker
            npm ci
            ts-node checkAll.ts
