version: 2

jobs:
  build1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          command: |
            echo 'hello'
            cd checker
            npm install
            npm run validate

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build1
