name: Node CI

on:
  schedule:
    - cron: 15,17,19 * * * *

jobs:
  validate-all-tasks:
    name: Validate All Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd checker
          npm install typescript
          npm ci
          ts-node checkAll.ts
